function varargout=sys_cstr(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('x',1:2,'p',3:6);
   return
  case 'argsize'
   varargout{1}=struct('x',2,'p',4);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=3;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('sys_cstr_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = sys_cstr_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_CSTR_RHS_0
%    [OUT1,OUT2] = SYS_CSTR_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Sep-2024 20:02:39

t2 = in2.*in3;
t3 = in1-1.0;
t4 = t2+1.0;
t5 = 1.0./t4;
t6 = in2.*t5;
t7 = exp(t6);
t8 = t3.*t7;
out1 = -t8-in1./in5;
if nargout > 1
    out2 = -(t8+in2./in6)./in4;
end
end


function [out1,out2] = sys_cstr_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_CSTR_RHS_1
%    [OUT1,OUT2] = SYS_CSTR_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Sep-2024 20:02:39

t2 = in2.*in3;
t3 = in2.*in9;
t4 = in3.*in8;
t5 = in1-1.0;
t6 = 1.0./in6;
t7 = t2+1.0;
t8 = t3+t4;
t9 = 1.0./t7;
t10 = t9.^2;
t11 = in2.*t9;
t12 = in8.*t9;
t13 = exp(t11);
t15 = in2.*t8.*t10;
t14 = in7.*t13;
t16 = -t15;
t17 = t12+t16;
t18 = t5.*t13.*t17;
out1 = -t14-t18-in7./in5+in1.*1.0./in5.^2.*in11;
if nargout > 1
    out2 = -(t14+t18+in8.*t6-in2.*in12.*t6.^2)./in4+1.0./in4.^2.*in10.*(in2.*t6+t5.*t13);
end
end


function [out1,out2] = sys_cstr_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_CSTR_RHS_2
%    [OUT1,OUT2] = SYS_CSTR_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Sep-2024 20:02:39

t2 = in2.*in3;
t3 = in2.*in9;
t4 = in3.*in8;
t5 = in1-1.0;
t6 = 1.0./in6;
t7 = t6.^2;
t8 = t2+1.0;
t9 = t3+t4;
t10 = 1.0./t8;
t13 = t9.^2;
t11 = t10.^2;
t12 = t10.^3;
t14 = in2.*t10;
t15 = in8.*t10;
t16 = exp(t14);
t17 = in8.*t3.*t11.*2.0;
t18 = in2.*t9.*t11;
t19 = in8.*t9.*t11.*2.0;
t21 = in2.*t12.*t13.*2.0;
t20 = -t18;
t22 = -t21;
t23 = t15+t20;
t27 = t17+t19+t22;
t24 = t23.^2;
t25 = in7.*t16.*t23.*2.0;
t28 = t5.*t16.*t27;
t26 = t5.*t16.*t24;
out1 = -t25-t26+t28-in1.*1.0./in5.^3.*in11.^2.*2.0+1.0./in5.^2.*in7.*in11.*2.0;
if nargout > 1
    out2 = -(t25+t26-t28+in2.*in12.^2.*t6.^3.*2.0-in8.*in12.*t7.*2.0)./in4+1.0./in4.^2.*in10.*(in8.*t6+in7.*t16-in2.*in12.*t7+t5.*t16.*t23).*2.0-1.0./in4.^3.*in10.^2.*(in2.*t6+t5.*t16).*2.0;
end
end


function [out1,out2] = sys_cstr_rhs_3(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_CSTR_RHS_3
%    [OUT1,OUT2] = SYS_CSTR_RHS_3(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Sep-2024 20:02:39

t2 = in2.*in3;
t3 = in2.*in9;
t4 = in3.*in8;
t5 = in8.^2;
t6 = in12.^2;
t7 = in1-1.0;
t8 = 1.0./in6;
t9 = t8.^2;
t10 = t8.^3;
t11 = t2+1.0;
t12 = t3+t4;
t13 = 1.0./t11;
t17 = t12.^2;
t18 = t12.^3;
t14 = t13.^2;
t15 = t13.^3;
t19 = in2.*t13;
t20 = in8.*t13;
t16 = t14.^2;
t21 = exp(t19);
t22 = in8.*t3.*t14.*2.0;
t23 = in9.*t5.*t14.*6.0;
t24 = in2.*t12.*t14;
t25 = in8.*t12.*t14.*2.0;
t27 = in2.*t15.*t17.*2.0;
t29 = in8.*t15.*t17.*6.0;
t30 = in8.*t3.*t12.*t15.*1.2e+1;
t26 = -t24;
t28 = in2.*t16.*t18.*6.0;
t31 = -t27;
t32 = -t29;
t33 = -t30;
t34 = t20+t26;
t41 = t22+t25+t31;
t43 = t23+t28+t32+t33;
t35 = t34.^2;
t36 = t34.^3;
t42 = in7.*t21.*t41.*3.0;
t44 = t7.*t21.*t43;
t45 = t7.*t21.*t34.*t41.*3.0;
t37 = in7.*t21.*t35.*3.0;
t39 = t7.*t21.*t36;
t38 = -t37;
t40 = -t39;
out1 = t38+t40+t42+t44+t45+in1.*1.0./in5.^4.*in11.^3.*6.0-1.0./in5.^3.*in7.*in11.^2.*6.0;
if nargout > 1
    out2 = (t38+t40+t42+t44+t45+in2.*in12.^3.*t9.^2.*6.0-in8.*t6.*t10.*6.0)./in4-1.0./in4.^3.*in10.^2.*(in8.*t8+in7.*t21-in2.*in12.*t9+t7.*t21.*t34).*6.0+1.0./in4.^2.*in10.*(in8.*in12.*t9.*-2.0+in2.*t6.*t10.*2.0+in7.*t21.*t34.*2.0+t7.*t21.*t35-t7.*t21.*t41).*3.0+1.0./in4.^4.*in10.^3.*(in2.*t8+t7.*t21).*6.0;
end
end

